spring:
  application:
    name: auth-lib
  datasource:
    url: ${DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


security:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:'*'}

  jwt:
    secret: ${JWT_SECRET}
    expiration-access-token: ${EXPIRATION_ACCESS_TOKEN}
    expiration-refresh-token: ${EXPIRATION_REFRESH_TOKEN}